# -*- coding: utf-8 -*-
"""Fetch_current_weather

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B38PG7fd0t2j_JHW4y3vDEL73J078JYb

## Fetch Weather Information Using OpenWeatherMap API
This Python script fetches current weather details for a specified location using the OpenWeatherMap API. It prompts the user to enter a zip code, makes an API request and displays relevant weather information.


*   Dependencies:
>- requests library for making HTTP requests.


*  API Usage:
>- OpenWeatherMap API key required for authentication.

*  Usage:
>- Replace 'YOUR_API_KEY' with a valid OpenWeatherMap API key.
>- Enter the desired zip code when prompted.
>- It displays current temperature, weather description, humidity and wind speed.

*  Note:
>- Customize 'units' parameter in the API request for temperature units (metric for Celsius, imperial for Fahrenheit).
>- Ensure a stable internet connection for successful API requests.

* Author:
>- Jerome Acolatse
"""

import requests

def get_weather(api_key, zip_code):
    base_url = "http://api.openweathermap.org/data/2.5/weather"

    # Creating parameters for the API request
    params = {
        'zip': f'{zip_code},de',  #You can change 'de' to the appropriate country code
        'appid': api_key,
        'units': 'metric'  # Use 'imperial' for Fahrenheit
    }

    try:
        # Making the API request
        response = requests.get(base_url, params=params)
        data = response.json()

        # Check if the request was successful
        if response.status_code == 200:  #200 means it is okay
            # Print relevant weather information
            print(f"Weather in {data['name']}, {data['sys']['country']}:")
            print(f"Temperature: {data['main']['temp']}°C")
            print(f"Description: {data['weather'][0]['description']}")
            print(f"Humidity: {data['main']['humidity']}%")
            print(f"Wind Speed: {data['wind']['speed']} m/s")
        else:
            print(f"Error: {data['message']}")

    except Exception as e:
        print(f"An error occurred: {e}")

#the API key you obtain
api_key = 'YOUR_API_KEY'

# Your desired zip code
zip_code = 'YOUR_DESIRED_ZIP_CODE'

get_weather(api_key, zip_code)

